In [7]:
#Question 1 ->
import numpy as np
a=np.array([[1,2,3,4],[5,6,7,8]])
print(a)
#b=np.T(a)
print(a.transpose())

[[1 2 3 4]
 [5 6 7 8]]
[[1 5]
 [2 6]
 [3 7]
 [4 8]]


In [11]:
#Question 2->
import numpy as np

a=np.array([1,2,3,4,5,6,7,8,9,10])
print(a)
a=a.reshape(2,5)
print("2*5  \n "  ,a)
a=a.reshape(5,2)
print("5*2\n",a)

[ 1  2  3  4  5  6  7  8  9 10]
2*5  
  [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
5*2
 [[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


In [12]:
#Question 3 ->

import numpy as np


original_array = np.random.rand(4, 4)

print("Original 4x4 array:")
print(original_array)
print()

larger_array = np.zeros((6, 6))

larger_array[1:5, 1:5] = original_array

print("Resulting 6x6 array with zeros border:")
print(larger_array)


Original 4x4 array:
[[0.88660358 0.77339644 0.92692813 0.78522275]
 [0.09371761 0.61805828 0.43086547 0.27262776]
 [0.47487769 0.06324925 0.26943891 0.39331922]
 [0.50659023 0.5110529  0.69607073 0.96114372]]

Resulting 6x6 array with zeros border:
[[0.         0.         0.         0.         0.         0.        ]
 [0.         0.88660358 0.77339644 0.92692813 0.78522275 0.        ]
 [0.         0.09371761 0.61805828 0.43086547 0.27262776 0.        ]
 [0.         0.47487769 0.06324925 0.26943891 0.39331922 0.        ]
 [0.         0.50659023 0.5110529  0.69607073 0.96114372 0.        ]
 [0.         0.         0.         0.         0.         0.        ]]


In [3]:
#Question 4 - >

import numpy as np

a=np.arange(10,50)
b=np.array(a)
b=b.reshape(8,5)
print("aranged",b)

aranged [[10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]
 [30 31 32 33 34]
 [35 36 37 38 39]
 [40 41 42 43 44]
 [45 46 47 48 49]]


In [14]:
#Question 5 ->>
a= ['python', 'numpy', 'pandas']
b="mayank"
print(a)
c=[x.upper() for x in a]
print(c)

['python', 'numpy', 'pandas']
['PYTHON', 'NUMPY', 'PANDAS']


In [4]:
#Question 6 ->
# importing numpy as np 
import numpy as np 


x = np.array(["geeks", "for", "geeks"]) 
print("Printing the Original Array:") 
print(x) 

r = np.char.join(" ", x) 
print("Printing the array after inserting space\ between the elements") 
print(r) 


Printing the Original Array:
['geeks' 'for' 'geeks']
Printing the array after inserting space\ between the elements
['g e e k s' 'f o r' 'g e e k s']


In [7]:
#Question 7 ->>
import numpy as np
a=np.array([[1,2,3],[4,5,6]])
b=np.array([[1,2,3],[4,5,6]])
c=a+b
d=a-b
e=a/b
print(c,"\n",d)


[[ 2  4  6]
 [ 8 10 12]] 
 [[0 0 0]
 [0 0 0]]


In [11]:
#question 8 ->>
# Python code to print identity matrix

# Function to print identity matrix
def Identity(size):
	for row in range(0, size):
		for col in range(0, size):

			# Here end is used to stay in same line
			if (row == col):
				print("1 ", end=" ")
			else:
				print("0 ", end=" ")
		print()

# Driver Code	 
size = 4
Identity(size)


1  0  0  0  
0  1  0  0  
0  0  1  0  
0  0  0  1  


In [4]:
#question 10 ->>
a=[i for i in range(100)]
for i in a:
    for j in range(2,101):
        if i%j==0:
            break
    if i==j:
        print(i,end =" , ")
        



2 , 3 , 5 , 7 , 11 , 13 , 17 , 19 , 23 , 29 , 31 , 37 , 41 , 43 , 47 , 53 , 59 , 61 , 67 , 71 , 73 , 79 , 83 , 89 , 97 , 