Question 1 ->
NumPy is an indispensable tool for scientific computing, data analysis, and numerical computations in Python. Its ability to efficiently handle arrays, perform complex mathematical operations, and seamlessly integrate with other libraries..


Question 2 ->
n the Numpy library, there are two functions np.mean() and np.average() are present. Both are actually doing nearly the same job of calculating mean/average. The difference comes when we are calculating the weighted average. If that is the case then we have to use np.average(). With np.average function we can calculate both arithmetic mean and weighted average. In this article, we have shown the basic use case of both functions and how they are different from each other.

Question 3 - >
To reverse an array we use flip fuction.


In [4]:
import numpy as np
a=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(type(a))
print("before",a)
a=np.flip(a)
print("after",a)


<class 'numpy.ndarray'>
before [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
after [[10  9  8  7  6]
 [ 5  4  3  2  1]]


Question 4 ->
To determine the data type of a element id by dtype ..
It is use for knowing about the how many byte it will take to store ythe data itme..


In [9]:
import numpy as np
a=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(type(a))
print(a.dtype)


<class 'numpy.ndarray'>
int64


Question 5 ->
NumPy arrays have a fixed size at creation, unlike Python lists (which can grow dynamically). Changing the size of an ndarray will create a new array and delete the original. The elements in a NumPy array are all required to be of the same data type, and thus will be the same size in memory.

Question 6 ->
NumPy arrays are homogeneous and contiguous in memory, allowing for optimized processing with compiled C code. This results in faster execution times for mathematical operations and array manipulations compared to Python lists, particularly when dealing with large datasets or complex numerical computations.

Question 7 ->
The major difference is that np. hstack combines NumPy arrays horizontally and np. vstack combines arrays vertically.

In [10]:
import numpy as np
a=np.array([1,2,3,4,5])
b=np.array([6,7,8,9,10])
a=np.hstack(a)
b=np.vstack(b)
print(a)
print(b)

[1 2 3 4 5]
[[ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]]


Question 8 ->
fliplr(a) that corresponds to np. flip(a, axis=1) . flipud can only flip an array along the vertical axis and flip will flip along a given axis.

In [14]:
import numpy as geek 
array = geek.arange(8).reshape((2,2,2)) 
print("Original array : \n", array)  
print("\nFlipped array left-right : \n", geek.fliplr(array)) 


Original array : 
 [[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]

Flipped array left-right : 
 [[[2 3]
  [0 1]]

 [[6 7]
  [4 5]]]


Question 9 ->
numpy.split() is a function that divides an array into equal parts along a specified axis. The code imports NumPy creates an array of numbers (0-5), and then splits it in half (horizontally) using np.split()

In [15]:
import numpy as np
array = np.arange(6)

result = np.split(array, 2)

print("Array:")
print(array)
print("\nResult after numpy.split():")
print(result)


Array:
[0 1 2 3 4 5]

Result after numpy.split():
[array([0, 1, 2]), array([3, 4, 5])]


Question 10 ->
Broadcasting provides a means for vectorizing the array operations so that looping would take place in C. It is a mechanism used by Numpy when it has to perform arithmetic operations on arrays with different shapes. Usual numpy broadcasting operations on two arrays are done on an element-by-element basis.